# Generated by Django 3.2.3 on 2021-06-20 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20210620_1801'),
    ]

    operations = [
        migrations.RenameField(
            model_name='whichmrtname',
            old_name='Object',
            new_name='Title',
        ),
    ]
