# Generated by Django 3.2.3 on 2021-06-20 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_rename_object_whichmrtname_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WhichMrtName',
        ),
    ]
