# Generated by Django 3.2.3 on 2021-06-26 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_whichmrtname_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whichmrtname',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
